server {
    listen 80;
    server_name crimewars.wrds361.com;

    location /static/ {
        alias /app/static/;
        expires 7d;
        add_header Cache-Control "public, immutable";
    }

    location /uploads/ {
        alias /app/uploads/;
        expires 30d;
    }

    location /socket.io/ {
        set $games_backend http://web:5000;
        proxy_pass         $games_backend;
        proxy_http_version 1.1;
        proxy_set_header   Upgrade $http_upgrade;
        proxy_set_header   Connection "Upgrade";
        proxy_set_header   Host $host;
        proxy_buffering    off;
    }

    resolver 127.0.0.11 valid=10s;

    location / {
        set $games_backend http://web:5000;
        proxy_pass         $games_backend;
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
        proxy_read_timeout 120s;
    }
}
